name: Run Selenium Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.3.0'

    - name: Check Node.js version
      run: node --version

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
        wget https://chromedriver.storage.googleapis.com/91.0.4472.101/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        pip install -r requirements.txt
        pip install selenium

    - name: Verify Chrome and Chromedriver installation
      run: |
        google-chrome --version
        chromedriver --version
        which google-chrome
        which chromedriver
        ls -al /usr/local/bin/
        echo $PATH

    - name: Run tests
      run: python -m unittest discover -s tests
      env:
        PATH: /usr/local/bin:$PATH

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test_results.txt
